/**
 * Card back catalog. PURE DATA — no image `require()`, so this stays safe to
 * import from the server bundle.
 *
 * The artwork itself is generated by `assets/brand/card-backs.js`; the image map
 * lives in `components/CardSprite.tsx` because `require()` of a PNG is a Metro
 * thing. `tests/unit/card-backs.test.ts` keeps the three in sync.
 */

export type CardBackId = 'verde' | 'vermelho' | 'azul' | 'vinho' | 'grafite' | 'roxo';

/** Display order in Settings. */
export const CARD_BACK_IDS: readonly CardBackId[] = [
  'verde',
  'vermelho',
  'azul',
  'vinho',
  'grafite',
  'roxo',
];

/** Green, matching the app's brand colour. */
export const DEFAULT_CARD_BACK: CardBackId = 'verde';

/**
 * Narrows a persisted value. Settings survive app upgrades and can be hand
 * edited, so an unknown id falls back rather than rendering an undefined image.
 */
export function toCardBackId(value: unknown): CardBackId {
  return CARD_BACK_IDS.includes(value as CardBackId) ? (value as CardBackId) : DEFAULT_CARD_BACK;
}
