import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { CARD_ASPECT } from '../../shared/lib/brisca/card-metrics';
import { CARD_BACK_IDS } from '../../shared/lib/brisca/card-backs';

/**
 * Guards the card art contract. The faces are generated by
 * `scripts/extract-cards.mjs`, the backs by `assets/brand/gen-assets.js`, and
 * both are then re-encoded by `scripts/webp-cards.mjs`; all three are one-off
 * commands, so nothing else would notice if a run half-failed or if someone
 * dropped a differently-proportioned file in.
 */
const DIR = path.resolve(__dirname, '../../assets/images/spanish');
const SUITS = ['oros', 'copas', 'espadas', 'bastos'];
const RANKS = [1, 2, 3, 4, 5, 6, 7, 10, 11, 12];

/** Faces: so a 190dp card on a @3x tablet (570px) is never upscaled. */
const MIN_FACE_WIDTH = 600;
/**
 * Backs: they only ever render at the `small`/`deck` metric, and `small` is half
 * of `large`, which is capped at 190dp — a hard ceiling of 95dp, or 285px @3x.
 * Holding backs to the face threshold cost ~96KB each for no visible gain.
 */
const MIN_BACK_WIDTH = 300;

/**
 * Ceiling per file, in bytes.
 *
 * The art is WebP rather than PNG because the PNG set reached 6.75MB — 169KB a
 * card, peaking at 350KB — and a deck that size cannot stay in the decoded-bitmap
 * cache, so cards were being re-decoded as they were dealt. Re-encoding got the
 * set to 2.34MB. This guards the property that actually matters at runtime: no
 * single card may quietly grow back past what the budget assumed. The heaviest
 * face after conversion is 07-oros at 111KB.
 */
const MAX_FACE_BYTES = 160 * 1024;

const FACES = SUITS.flatMap((suit) =>
  RANKS.map((rank) => `${String(rank).padStart(2, '0')}-${suit}.webp`),
);
const BACKS = CARD_BACK_IDS.map((id) => `reverso-${id}.webp`);
const FILES = [...FACES, ...BACKS];

/**
 * Reads width/height out of a WebP VP8X header, and asserts the alpha flag.
 *
 * Transparency is the property worth guarding: the art carries its own rounded
 * white face on a transparent background, so a card that came back flattened
 * would render as a white rectangle sitting on the green felt. It is read as the
 * VP8X feature bit rather than by looking for an `ALPH` chunk, because lossless
 * WebP keeps alpha inside `VP8L` and emits no `ALPH` — checking for the chunk
 * would fail the moment anyone runs the converter at `--quality=1`.
 */
function webpSize(file: string) {
  const buf = fs.readFileSync(path.join(DIR, file));
  expect(buf.subarray(0, 4).toString('ascii'), `${file} não é RIFF`).toBe('RIFF');
  expect(buf.subarray(8, 12).toString('ascii'), `${file} não é WebP`).toBe('WEBP');
  expect(buf.subarray(12, 16).toString('ascii'), `${file} sem VP8X`).toBe('VP8X');
  // Byte 20 is the VP8X feature-flag byte; 0x10 is alpha.
  expect(buf[20] & 0x10, `${file} perdeu a transparência`).toBe(0x10);
  // VP8X stores each dimension minus one, as 24-bit little-endian.
  return { width: buf.readUIntLE(24, 3) + 1, height: buf.readUIntLE(27, 3) + 1 };
}

describe('arte das cartas', () => {
  it('tem exatamente os arquivos que o app carrega, e nada além', () => {
    expect(fs.readdirSync(DIR).sort()).toEqual([...FILES].sort());
  });

  it.each(FACES)('face %s é grande o bastante para tablet', (file) => {
    expect(webpSize(file).width).toBeGreaterThanOrEqual(MIN_FACE_WIDTH);
  });

  it.each(BACKS)('verso %s é grande o bastante para o tamanho em que aparece', (file) => {
    expect(webpSize(file).width).toBeGreaterThanOrEqual(MIN_BACK_WIDTH);
  });

  it.each(FACES)('face %s não voltou a pesar como PNG', (file) => {
    expect(fs.statSync(path.join(DIR, file)).size).toBeLessThanOrEqual(MAX_FACE_BYTES);
  });

  it('todos os arquivos têm a mesma proporção, e ela bate com CARD_ASPECT', () => {
    // The backs are generated from SVG rather than sliced from the purchased
    // sheets, so they are the files most likely to drift out of proportion —
    // and a back that does not match the faces is obvious at the table.
    for (const file of FILES) {
      const { width, height } = webpSize(file);
      expect(height / width, file).toBeCloseTo(CARD_ASPECT, 2);
    }
  });

  it('não sobrou nada da arte CC BY-SA anterior', () => {
    const names = fs.readdirSync(DIR);
    expect(names).not.toContain('Baraja_española_completa.png');
    expect(names.filter((n) => /^(08|09)-/.test(n))).toEqual([]);
  });
});
